POST http://localhost:5000/login
content-type: application/json

{
    "username":"VIlle",
    "password":"123"
}
###

GET http://localhost:5000/logout
content-type: application/json

###

POST http://localhost:5000/register
content-type: application/json

{
    "username":"VIlleNunese",
    "password":"123"
}


###

GET http://localhost:5000/users/1


